import type { HeroLayout, ProcessLayout } from '@/lib/products/design'
import type { ServiceSlug } from './types'

export type ServiceDesign = {
  heroLayout: HeroLayout
  processLayout: ProcessLayout
  motifLabel: string
  signalWord: string
  accentNote: string
  challengesVariant: 'grid' | 'stacked' | 'columns'
  outcomesVariant: 'cards' | 'strip' | 'editorial'
  capabilitiesVariant: 'two-col' | 'dense' | 'featured'
  faqVariant: 'boxed' | 'wide' | 'editorial'
  ctaVariant: 'centered' | 'split' | 'minimal' | 'wide' | 'signal'
  sectionOrder: Array<
    'whoFor' | 'challenges' | 'outcomes' | 'capabilities' | 'process' | 'faqs' | 'related'
  >
}

export const SERVICE_DESIGNS: Record<ServiceSlug, ServiceDesign> = {
  'ai-reputation-management': {
    heroLayout: 'split-orbit',
    processLayout: 'timeline',
    motifLabel: 'AI surfaces',
    signalWord: 'Narrative',
    accentNote: 'Monitor · Correct · Reinforce · Measure',
    challengesVariant: 'grid',
    outcomesVariant: 'cards',
    capabilitiesVariant: 'featured',
    faqVariant: 'boxed',
    ctaVariant: 'centered',
    sectionOrder: [
      'whoFor',
      'challenges',
      'capabilities',
      'process',
      'outcomes',
      'faqs',
      'related',
    ],
  },
  'executive-branding': {
    heroLayout: 'briefing-panel',
    processLayout: 'rail',
    motifLabel: 'Executive identity',
    signalWord: 'Presence',
    accentNote: 'Position · Publish · Amplify · Protect',
    challengesVariant: 'columns',
    outcomesVariant: 'editorial',
    capabilitiesVariant: 'two-col',
    faqVariant: 'editorial',
    ctaVariant: 'minimal',
    sectionOrder: [
      'process',
      'whoFor',
      'capabilities',
      'outcomes',
      'challenges',
      'faqs',
      'related',
    ],
  },
  'review-management': {
    heroLayout: 'concierge-wide',
    processLayout: 'steps-wide',
    motifLabel: 'Review system',
    signalWord: 'Trust',
    accentNote: 'Listen · Respond · Request · Improve',
    challengesVariant: 'grid',
    outcomesVariant: 'strip',
    capabilitiesVariant: 'dense',
    faqVariant: 'wide',
    ctaVariant: 'wide',
    sectionOrder: [
      'challenges',
      'outcomes',
      'capabilities',
      'process',
      'whoFor',
      'faqs',
      'related',
    ],
  },
  'reddit-removal': {
    heroLayout: 'serp-signal',
    processLayout: 'serp-flow',
    motifLabel: 'Platform protocol',
    signalWord: 'Removal',
    accentNote: 'Assess · Document · Request · Verify',
    challengesVariant: 'stacked',
    outcomesVariant: 'cards',
    capabilitiesVariant: 'featured',
    faqVariant: 'boxed',
    ctaVariant: 'signal',
    sectionOrder: [
      'challenges',
      'process',
      'capabilities',
      'outcomes',
      'whoFor',
      'faqs',
      'related',
    ],
  },
  wikipedia: {
    heroLayout: 'centered-shield',
    processLayout: 'cards',
    motifLabel: 'Editorial standards',
    signalWord: 'Accuracy',
    accentNote: 'Research · Sources · Edit · Maintain',
    challengesVariant: 'stacked',
    outcomesVariant: 'editorial',
    capabilitiesVariant: 'two-col',
    faqVariant: 'editorial',
    ctaVariant: 'split',
    sectionOrder: [
      'capabilities',
      'whoFor',
      'process',
      'challenges',
      'outcomes',
      'faqs',
      'related',
    ],
  },
  'google-maps-seo': {
    heroLayout: 'split-orbit',
    processLayout: 'timeline',
    motifLabel: 'Local visibility',
    signalWord: 'Maps',
    accentNote: 'Claim · Optimize · Rank · Convert',
    challengesVariant: 'grid',
    outcomesVariant: 'cards',
    capabilitiesVariant: 'dense',
    faqVariant: 'wide',
    ctaVariant: 'centered',
    sectionOrder: [
      'outcomes',
      'capabilities',
      'process',
      'whoFor',
      'challenges',
      'faqs',
      'related',
    ],
  },
  'earned-media-marketing': {
    heroLayout: 'briefing-panel',
    processLayout: 'steps-wide',
    motifLabel: 'Editorial reach',
    signalWord: 'Authority',
    accentNote: 'Pitch · Place · Amplify · Sustain',
    challengesVariant: 'columns',
    outcomesVariant: 'editorial',
    capabilitiesVariant: 'featured',
    faqVariant: 'editorial',
    ctaVariant: 'wide',
    sectionOrder: [
      'whoFor',
      'capabilities',
      'process',
      'outcomes',
      'challenges',
      'faqs',
      'related',
    ],
  },
  'expert-witness-services': {
    heroLayout: 'serp-signal',
    processLayout: 'rail',
    motifLabel: 'Testimony readiness',
    signalWord: 'Expertise',
    accentNote: 'Brief · Evidence · Testify · Support',
    challengesVariant: 'stacked',
    outcomesVariant: 'cards',
    capabilitiesVariant: 'two-col',
    faqVariant: 'boxed',
    ctaVariant: 'minimal',
    sectionOrder: [
      'process',
      'capabilities',
      'whoFor',
      'outcomes',
      'challenges',
      'faqs',
      'related',
    ],
  },
  'personal-reputation-management': {
    heroLayout: 'centered-shield',
    processLayout: 'timeline',
    motifLabel: 'Personal brand',
    signalWord: 'Reputation',
    accentNote: 'Audit · Repair · Build · Protect',
    challengesVariant: 'grid',
    outcomesVariant: 'cards',
    capabilitiesVariant: 'featured',
    faqVariant: 'boxed',
    ctaVariant: 'centered',
    sectionOrder: [
      'challenges',
      'outcomes',
      'capabilities',
      'process',
      'whoFor',
      'faqs',
      'related',
    ],
  },
  'business-reputation-management': {
    heroLayout: 'concierge-wide',
    processLayout: 'cards',
    motifLabel: 'Brand trust',
    signalWord: 'Business',
    accentNote: 'Listen · Respond · Position · Scale',
    challengesVariant: 'grid',
    outcomesVariant: 'strip',
    capabilitiesVariant: 'dense',
    faqVariant: 'wide',
    ctaVariant: 'split',
    sectionOrder: [
      'whoFor',
      'capabilities',
      'process',
      'outcomes',
      'challenges',
      'faqs',
      'related',
    ],
  },
}

export function getServiceDesign(slug: ServiceSlug): ServiceDesign {
  return SERVICE_DESIGNS[slug]
}
